name: Write Wakatime svg

on:
  push:
  schedule:
    - cron: '0 4 * * *'
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  release:
    name: Wakatime
    runs-on: [ubuntu-latest]

    steps:
      - name: WakaTime
        uses: lowlighter/metrics@latest
        with:
          plugin_isocalendar: true
          plugin_languages: true
          plugin_lines: true
          plugin_reactions: true
          plugin_wakatime: true
          token: ${{ secrets.GH_TOKEN }}
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
